# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestWholeusagetest():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_wholeusagetest(self):
    # Go to site and validate title name
    self.driver.get("http://165.245.208.238:8080/OfekLamay_BenLetai_LinoyAvraham_TomerBiton_AmitHazan/index.jsp")
    assert self.driver.title == "DevOps Final Project"

    # Validate that there is a button in the page
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".btn")
    assert len(elements) > 0

    # Insert search word and validate that there is no error message
    self.driver.find_element(By.NAME, "q").click()
    self.driver.find_element(By.NAME, "q").send_keys("Linoy")
    time.sleep(2) # Sleep to show that the text is provided
    elements = self.driver.find_elements(By.ID, "error-message")
    assert len(elements) == 0

    # Validate that there is a link to github
    elements = self.driver.find_elements(By.CSS_SELECTOR, "a[href*=\'github.com\']")
    assert len(elements) > 0

    # Search with the text used in the test
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.XPATH, "//input[@value=\'חפש בגוגל\']").click()
    time.sleep(3) # Sleep to show the search results

    self.vars["win9999"] = self.wait_for_window(2000)
  
