# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFulltest():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    time.sleep(2)
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_fulltest(self):
    self.driver.get("http://165.245.208.238:8080/OfekLamay_BenLetai_LinoyAvraham_TomerBiton_AmitHazan/index.jsp")
    self.driver.set_window_size(934, 772)
    time.sleep(2)
    
    # Check that the link element exists and click on it 
    elements = self.driver.find_elements(By.LINK_TEXT, "צפייה בקוד")
    assert len(elements) > 0
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.LINK_TEXT, "צפייה בקוד").click()
    time.sleep(2)
    
    # Exit the new window and go back to the main web page
    self.vars["win180"] = self.wait_for_window(2000)
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win180"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
    time.sleep(1)
    
    # Check that the expenseName text box exists, click on it and add a value
    elements = self.driver.find_elements(By.ID, "expenseName")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "expenseName").click()
    self.driver.find_element(By.ID, "expenseName").send_keys("משקה")
    time.sleep(1)
    
    # Check that the amount input box exists, click on it and add a value
    elements = self.driver.find_elements(By.ID, "amount")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "amount").click()
    self.driver.find_element(By.ID, "amount").send_keys("25")
    time.sleep(1)
    
    # Verify that the number was inserted well, as a number
    entered_amount = amount_field.get_attribute("value")
    try:
        assert entered_amount.isdigit(), f"Verify Failed: Expected only numbers in amount, but got '{entered_amount}'"
        print("Verify Passed: Amount contains only numeric characters.")
    except AssertionError as e:
        print(e)
    
    # Check that the submit button exists and click on it
    elements = self.driver.find_elements(By.CSS_SELECTOR, "button")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    time.sleep(2)
    
    # Check that there are no errors
    error_elements = self.driver.find_elements(By.ID, "error-message")
    assert len(error_elements) == 0
    
    # Check that the clear button exists and click on it
    elements = self.driver.find_elements(By.LINK_TEXT, "נקה נתונים")
    assert len(elements) > 0, "Clear data link is missing!"
    self.driver.find_element(By.LINK_TEXT, "נקה נתונים").click()
    self.vars["window_handles"] = self.driver.window_handles
    time.sleep(2)
    
    # Closing
    self.vars["win3901"] = self.wait_for_window(2000)
    self.vars["window_handles"] = self.driver.window_handles
    
